const sb=supabase.createClient(window.SUPABASE_URL,window.SUPABASE_ANON_KEY);
let user,cats=[],accounts=[],cards=[],recurring=[],goals=[],txs=[],flowChart,catChart;
const $=x=>document.getElementById(x),today=new Date().toISOString().slice(0,10),thisMonth=today.slice(0,7);
const money=n=>Number(n||0).toLocaleString("pt-BR",{style:"currency",currency:"BRL"});
const esc=s=>String(s??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]));
function msg(id,t){$(id).textContent=t||""}
document.addEventListener("DOMContentLoaded",async()=>{
$("dashMonth").value=thisMonth;$("reportMonth").value=thisMonth;$("txDate").value=today;
$("loginForm").onsubmit=login;$("signupForm").onsubmit=signup;$("logout").onclick=()=>sb.auth.signOut();
$("txForm").onsubmit=saveTx;$("cardForm").onsubmit=saveCard;$("recForm").onsubmit=saveRec;$("goalForm").onsubmit=saveGoal;$("accountForm").onsubmit=saveAccount;
$("dashMonth").onchange=dashboard;$("reportMonth").onchange=report;$("excel").onclick=excel;$("pdf").onclick=pdf;
document.querySelectorAll("nav button").forEach(b=>b.onclick=()=>page(b.dataset.page));
let s=(await sb.auth.getSession()).data.session;if(s)start(s.user);else loginView();sb.auth.onAuthStateChange((e,s)=>s?start(s.user):loginView())});
function loginView(){$("loginView").classList.remove("hidden");$("app").classList.add("hidden")}
async function start(u){user=u;let r=await sb.from("profiles").select("*").eq("id",u.id).maybeSingle();$("userName").textContent=r.data?.name||u.email;$("loginView").classList.add("hidden");$("app").classList.remove("hidden");await load();page("dashboard")}
async function login(e){e.preventDefault();let r=await sb.auth.signInWithPassword({email:$("loginEmail").value,password:$("loginPassword").value});if(r.error)msg("authMsg",r.error.message)}
async function signup(e){e.preventDefault();let r=await sb.auth.signUp({email:$("signupEmail").value,password:$("signupPassword").value,options:{data:{name:$("signupName").value}}});msg("authMsg",r.error?.message||"Conta criada.")}
async function load(){let [a,b,c,d,e,f]=await Promise.all([sb.from("categories").select("*").order("name"),sb.from("accounts").select("*").order("name"),sb.from("cards").select("*").order("name"),sb.from("recurring").select("*,categories(name)").order("description"),sb.from("goals").select("*").order("created_at",{ascending:false}),sb.from("transactions").select("*,categories(name),accounts(name),cards(name)").order("transaction_date",{ascending:false}).limit(3000)]);cats=a.data||[];accounts=b.data||[];cards=c.data||[];recurring=d.data||[];goals=e.data||[];txs=f.data||[];fill();render()}
function fill(){$("txCat").innerHTML=cats.map(c=>`<option value="${c.id}">${esc(c.name)}</option>`).join("");$("recCat").innerHTML=$("txCat").innerHTML;$("txAccount").innerHTML=accounts.map(a=>`<option value="${a.id}">${esc(a.name)}</option>`).join("");$("txCard").innerHTML='<option value="">Nenhum</option>'+cards.map(c=>`<option value="${c.id}">${esc(c.name)}</option>`).join("")}
async function saveTx(e){e.preventDefault();let n=+$("txInstall").value||1,g=crypto.randomUUID(),base={user_id:user.id,type:$("txType").value,amount:+$("txAmount").value,transaction_date:$("txDate").value,category_id:$("txCat").value,account_id:$("txAccount").value||null,card_id:$("txCard").value||null,status:$("txStatus").value,description:$("txDesc").value,notes:$("txNotes").value||null,group_id:g};let rows=[];for(let i=0;i<n;i++){let d=new Date($("txDate").value+"T12:00:00");d.setMonth(d.getMonth()+i);rows.push({...base,transaction_date:d.toISOString().slice(0,10),installment_number:i+1,installment_total:n})}let r=await sb.from("transactions").insert(rows);msg("txMsg",r.error?.message||"Lançamento salvo.");if(!r.error){$("txForm").reset();$("txDate").value=today;await load()}}
async function saveCard(e){e.preventDefault();let r=await sb.from("cards").insert({user_id:user.id,name:$("cardName").value,limit_amount:+$("cardLimit").value,closing_day:+$("cardClose").value,due_day:+$("cardDue").value});msg("cardMsg",r.error?.message||"Cartão cadastrado.");if(!r.error){$("cardForm").reset();await load()}}
async function saveRec(e){e.preventDefault();let r=await sb.from("recurring").insert({user_id:user.id,description:$("recDesc").value,amount:+$("recAmount").value,category_id:$("recCat").value,due_day:+$("recDay").value,start_date:$("recStart").value,end_date:$("recEnd").value||null});msg("recMsg",r.error?.message||"Cadastrado.");if(!r.error){$("recForm").reset();await load()}}
async function saveGoal(e){e.preventDefault();let r=await sb.from("goals").insert({user_id:user.id,name:$("goalName").value,target_amount:+$("goalTarget").value,current_amount:+$("goalCurrent").value||0,deadline:$("goalDate").value||null});msg("goalMsg",r.error?.message||"Meta cadastrada.");if(!r.error){$("goalForm").reset();await load()}}
async function saveAccount(e){e.preventDefault();let r=await sb.from("accounts").insert({user_id:user.id,name:$("accountName").value,type:$("accountType").value,initial_balance:+$("accountInitial").value||0});msg("accountMsg",r.error?.message||"Conta cadastrada.");if(!r.error){$("accountForm").reset();await load()}}
function render(){txBody.innerHTML=txs.slice(0,200).map(t=>`<tr><td>${t.transaction_date}</td><td>${t.type}</td><td>${esc(t.description)}</td><td>${esc(t.categories?.name||"-")}</td><td>${money(t.amount)}</td><td>${t.status}</td><td>${t.installment_total>1?t.installment_number+"/"+t.installment_total:"-"}</td></tr>`).join("");cardBody.innerHTML=cards.map(c=>{let u=txs.filter(t=>t.card_id===c.id&&t.type==="saida"&&t.transaction_date.startsWith(thisMonth)).reduce((a,t)=>a+ +t.amount,0);return`<tr><td>${esc(c.name)}</td><td>${money(c.limit_amount)}</td><td>${money(u)}</td><td>${money(Math.max(0,c.limit_amount-u))}</td><td>${c.closing_day}</td><td>${c.due_day}</td></tr>`}).join("");recBody.innerHTML=recurring.map(r=>`<tr><td>${esc(r.description)}</td><td>${money(r.amount)}</td><td>${esc(r.categories?.name||"-")}</td><td>${r.due_day}</td><td>${r.start_date}</td><td>${r.end_date||"-"}</td></tr>`).join("");goals.innerHTML=goalsData();accountBody.innerHTML=accounts.map(a=>{let m=txs.filter(t=>t.account_id===a.id).reduce((s,t)=>s+(t.type==="entrada"?1:-1)*+t.amount,0);return`<tr><td>${esc(a.name)}</td><td>${esc(a.type)}</td><td>${money(a.initial_balance)}</td><td>${money(m)}</td><td>${money(+a.initial_balance+m)}</td></tr>`}).join("");dashboard();report()}
function goalsData(){return goals.map(g=>{let p=Math.min(100,+g.current_amount/+g.target_amount*100);return`<div class="goal"><h3>${esc(g.name)}</h3><b>${money(g.current_amount)} / ${money(g.target_amount)}</b><div class="progress"><div style="width:${p}%"></div></div>${p.toFixed(1)}%${g.deadline?" · prazo "+g.deadline:""}</div>`}).join("")}
function dashboard(){let m=$("dashMonth").value||thisMonth,r=txs.filter(t=>t.transaction_date.startsWith(m)),ins=r.filter(t=>t.type==="entrada").reduce((s,t)=>s+ +t.amount,0),out=r.filter(t=>t.type==="saida").reduce((s,t)=>s+ +t.amount,0),pending=txs.filter(t=>t.type==="saida"&&t.status==="pendente"&&t.transaction_date>=today).reduce((s,t)=>s+ +t.amount,0);inTotal.textContent=money(ins);outTotal.textContent=money(out);result.textContent=money(ins-out);available.textContent=money(ins-out-pending);let daily={};r.forEach(t=>daily[t.transaction_date]=(daily[t.transaction_date]||0)+(t.type==="entrada"?+t.amount:-+t.amount));let cc={};r.filter(t=>t.type==="saida").forEach(t=>cc[t.categories?.name||"Outros"]=(cc[t.categories?.name||"Outros"]||0)+ +t.amount);flowChart?.destroy();catChart?.destroy();flowChart=new Chart(flow,{type:"line",data:{labels:Object.keys(daily),datasets:[{label:"Resultado",data:Object.values(daily)}]}});catChart=new Chart(cats,{type:"doughnut",data:{labels:Object.keys(cc),datasets:[{data:Object.values(cc)}]}});due.innerHTML=txs.filter(t=>t.type==="saida"&&t.status==="pendente").slice(0,5).map(t=>`<p>${t.transaction_date} · ${esc(t.description)}<br><b>${money(t.amount)}</b></p>`).join("")||"Nenhuma.";cardDash.innerHTML=cards.map(c=>`<p>${esc(c.name)} · ${money(txs.filter(t=>t.card_id===c.id&&t.type==="saida"&&t.transaction_date.startsWith(m)).reduce((s,t)=>s+ +t.amount,0))}</p>`).join("")||"Nenhum.";goalDash.innerHTML=goals.slice(0,5).map(g=>`<p>${esc(g.name)} · ${(g.current_amount/g.target_amount*100).toFixed(0)}%</p>`).join("")||"Nenhuma."}
function report(){let m=$("reportMonth").value||thisMonth,r=txs.filter(t=>t.transaction_date.startsWith(m)),i=r.filter(t=>t.type==="entrada").reduce((s,t)=>s+ +t.amount,0),o=r.filter(t=>t.type==="saida").reduce((s,t)=>s+ +t.amount,0);summary.innerHTML=`<p>Entradas <b>${money(i)}</b> · Saídas <b>${money(o)}</b> · Resultado <b>${money(i-o)}</b></p>`;reportBody.innerHTML=r.map(t=>`<tr><td>${t.transaction_date}</td><td>${t.type}</td><td>${esc(t.description)}</td><td>${esc(t.categories?.name||"-")}</td><td>${money(t.amount)}</td><td>${t.status}</td></tr>`).join("")}
function excel(){let m=$("reportMonth").value||thisMonth,r=txs.filter(t=>t.transaction_date.startsWith(m)).map(t=>({Data:t.transaction_date,Tipo:t.type,Descrição:t.description,Categoria:t.categories?.name||"",Conta:t.accounts?.name||"",Cartão:t.cards?.name||"",Valor:+t.amount,Status:t.status,Parcela:t.installment_total>1?`${t.installment_number}/${t.installment_total}`:""}));let ws=XLSX.utils.json_to_sheet(r),wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,ws,"Financeiro");XLSX.writeFile(wb,`financeiro-${m}.xlsx`)}
function pdf(){let m=$("reportMonth").value||thisMonth,r=txs.filter(t=>t.transaction_date.startsWith(m)),i=r.filter(t=>t.type==="entrada").reduce((s,t)=>s+ +t.amount,0),o=r.filter(t=>t.type==="saida").reduce((s,t)=>s+ +t.amount,0),D=window.jspdf.jsPDF,d=new D();d.text("Relatório Financeiro Pessoal",14,18);d.setFontSize(10);d.text(`Mês: ${m}`,14,27);d.text(`Entradas: ${money(i)}  Saídas: ${money(o)}  Resultado: ${money(i-o)}`,14,36);let y=47;r.forEach(t=>{if(y>285){d.addPage();y=15}d.text(`${t.transaction_date} | ${t.type} | ${String(t.description).slice(0,25)} | ${money(t.amount)}`,14,y);y+=6});d.save(`financeiro-${m}.pdf`)}
function page(p){document.querySelectorAll(".page").forEach(x=>x.classList.add("hidden"));$(p).classList.remove("hidden")}
